# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cairo_pb2 as cairo__pb2


class CAIROVMStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/starknet.CAIROVM/Call',
                request_serializer=cairo__pb2.CallRequest.SerializeToString,
                response_deserializer=cairo__pb2.CallResponse.FromString,
                )
        self.Address = channel.unary_unary(
                '/starknet.CAIROVM/Address',
                request_serializer=cairo__pb2.AddressRequest.SerializeToString,
                response_deserializer=cairo__pb2.AddressResponse.FromString,
                )


class CAIROVMServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Address(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CAIROVMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=cairo__pb2.CallRequest.FromString,
                    response_serializer=cairo__pb2.CallResponse.SerializeToString,
            ),
            'Address': grpc.unary_unary_rpc_method_handler(
                    servicer.Address,
                    request_deserializer=cairo__pb2.AddressRequest.FromString,
                    response_serializer=cairo__pb2.AddressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'starknet.CAIROVM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CAIROVM(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starknet.CAIROVM/Call',
            cairo__pb2.CallRequest.SerializeToString,
            cairo__pb2.CallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Address(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starknet.CAIROVM/Address',
            cairo__pb2.AddressRequest.SerializeToString,
            cairo__pb2.AddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
