# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cairo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61iro.proto\x12\x08starknet\x1a\x19google/protobuf/any.proto\"\xa3\x01\n\x0b\x43\x61llRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x31\n\x06params\x18\x02 \x03(\x0b\x32!.starknet.CallRequest.ParamsEntry\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x0c\x1a\x43\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\"4\n\x0c\x43\x61llResponse\x12$\n\x06result\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"\x8a\x01\n\x0e\x41\x64\x64ressRequest\x12\x0c\n\x04salt\x18\x01 \x01(\t\x12\x34\n\x16\x63onstructor_definition\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x1c\n\x14\x63onstructor_calldata\x18\x03 \x03(\r\x12\x16\n\x0e\x63\x61ller_address\x18\x05 \x01(\t\"\"\n\x0f\x41\x64\x64ressResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t2\x84\x01\n\x07\x43\x41IROVM\x12\x37\n\x04\x43\x61ll\x12\x15.starknet.CallRequest\x1a\x16.starknet.CallResponse\"\x00\x12@\n\x07\x41\x64\x64ress\x12\x18.starknet.AddressRequest\x1a\x19.starknet.AddressResponse\"\x00\x42\x15Z\x13./starknet;starknetb\x06proto3')



_CALLREQUEST = DESCRIPTOR.message_types_by_name['CallRequest']
_CALLREQUEST_PARAMSENTRY = _CALLREQUEST.nested_types_by_name['ParamsEntry']
_CALLRESPONSE = DESCRIPTOR.message_types_by_name['CallResponse']
_ADDRESSREQUEST = DESCRIPTOR.message_types_by_name['AddressRequest']
_ADDRESSRESPONSE = DESCRIPTOR.message_types_by_name['AddressResponse']
CallRequest = _reflection.GeneratedProtocolMessageType('CallRequest', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CALLREQUEST_PARAMSENTRY,
    '__module__' : 'cairo_pb2'
    # @@protoc_insertion_point(class_scope:starknet.CallRequest.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _CALLREQUEST,
  '__module__' : 'cairo_pb2'
  # @@protoc_insertion_point(class_scope:starknet.CallRequest)
  })
_sym_db.RegisterMessage(CallRequest)
_sym_db.RegisterMessage(CallRequest.ParamsEntry)

CallResponse = _reflection.GeneratedProtocolMessageType('CallResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALLRESPONSE,
  '__module__' : 'cairo_pb2'
  # @@protoc_insertion_point(class_scope:starknet.CallResponse)
  })
_sym_db.RegisterMessage(CallResponse)

AddressRequest = _reflection.GeneratedProtocolMessageType('AddressRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSREQUEST,
  '__module__' : 'cairo_pb2'
  # @@protoc_insertion_point(class_scope:starknet.AddressRequest)
  })
_sym_db.RegisterMessage(AddressRequest)

AddressResponse = _reflection.GeneratedProtocolMessageType('AddressResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSRESPONSE,
  '__module__' : 'cairo_pb2'
  # @@protoc_insertion_point(class_scope:starknet.AddressResponse)
  })
_sym_db.RegisterMessage(AddressResponse)

_CAIROVM = DESCRIPTOR.services_by_name['CAIROVM']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\023./starknet;starknet'
  _CALLREQUEST_PARAMSENTRY._options = None
  _CALLREQUEST_PARAMSENTRY._serialized_options = b'8\001'
  _CALLREQUEST._serialized_start=53
  _CALLREQUEST._serialized_end=216
  _CALLREQUEST_PARAMSENTRY._serialized_start=149
  _CALLREQUEST_PARAMSENTRY._serialized_end=216
  _CALLRESPONSE._serialized_start=218
  _CALLRESPONSE._serialized_end=270
  _ADDRESSREQUEST._serialized_start=273
  _ADDRESSREQUEST._serialized_end=411
  _ADDRESSRESPONSE._serialized_start=413
  _ADDRESSRESPONSE._serialized_end=447
  _CAIROVM._serialized_start=450
  _CAIROVM._serialized_end=582
# @@protoc_insertion_point(module_scope)
